// Chhattisgadhiya Cloud service worker. Generated by generate-pages.js; do not edit by hand.
const VERSION = 'v7';
const SHELL = 'cc-shell-' + VERSION;
const PAGES = 'cc-pages-' + VERSION;
const ASSETS = 'cc-assets-' + VERSION;
const FONTS = 'cc-fonts-v1';
const KEEP = [SHELL, PAGES, ASSETS, FONTS];
const BASE = new URL('./', self.location).pathname;
const PRECACHE = [
  "en/",
  "hi/",
  "offline.html",
  "manifest.webmanifest",
  "favicon.svg",
  "src/assets/icons/icon-192.png",
  "src/assets/icons/icon-512.png",
  "src/site/site.css?v=7",
  "src/site/site.js?v=7",
  "src/home/home.css?v=7",
  "src/assets/images/hero-art.svg",
  "src/assets/images/motif-border.svg",
  "src/assets/images/footer-art-frieze.svg"
].map((p) => BASE + p);
const OFFLINE = BASE + 'offline.html';
const MAX_PAGES = 40;

self.addEventListener('install', (event) => {
  event.waitUntil(
    caches.open(SHELL)
      .then((cache) => Promise.all(PRECACHE.map((url) => cache.add(url).catch(() => null))))
      // If storage is unavailable, still activate: the site then simply works online.
      .catch(() => null)
      .then(() => self.skipWaiting())
  );
});

self.addEventListener('activate', (event) => {
  event.waitUntil((async () => {
    const keys = await caches.keys();
    await Promise.all(keys.filter((k) => !KEEP.includes(k)).map((k) => caches.delete(k)));
    if (self.registration.navigationPreload) await self.registration.navigationPreload.enable();
    await self.clients.claim();
  })());
});

async function trim(cacheName, max) {
  const cache = await caches.open(cacheName);
  const keys = await cache.keys();
  for (let i = 0; i < keys.length - max; i++) await cache.delete(keys[i]);
}

async function networkFirstPage(event) {
  try {
    const response = (await event.preloadResponse) || (await fetch(event.request));
    if (response && response.ok) {
      const copy = response.clone();
      caches.open(PAGES).then((c) => c.put(event.request, copy)).then(() => trim(PAGES, MAX_PAGES)).catch(() => null);
    }
    return response;
  } catch (err) {
    const cached = await caches.match(event.request, { ignoreSearch: true }).catch(() => null);
    return cached
      || (await caches.match(OFFLINE).catch(() => null))
      || new Response('Offline', { status: 503, headers: { 'Content-Type': 'text/plain' } });
  }
}

async function staleWhileRevalidate(request, cacheName) {
  const cache = await caches.open(cacheName);
  const cached = await cache.match(request);
  const network = fetch(request).then((response) => {
    if (response && (response.ok || response.type === 'opaque')) cache.put(request, response.clone());
    return response;
  }).catch(() => cached);
  return cached || network;
}

async function cacheFirst(request, cacheName) {
  const cache = await caches.open(cacheName);
  const cached = await cache.match(request);
  if (cached) return cached;
  const response = await fetch(request);
  if (response && (response.ok || response.type === 'opaque')) cache.put(request, response.clone());
  return response;
}

self.addEventListener('fetch', (event) => {
  const { request } = event;
  if (request.method !== 'GET') return;
  const url = new URL(request.url);
  if (url.origin === self.location.origin) {
    if (url.pathname.startsWith(BASE + 'admin/')) return;
    if (request.mode === 'navigate') { event.respondWith(networkFirstPage(event)); return; }
    event.respondWith(caches.match(request).then((hit) => hit || staleWhileRevalidate(request, ASSETS)).catch(() => fetch(request)));
    return;
  }
  if (url.hostname === 'fonts.googleapis.com') { event.respondWith(staleWhileRevalidate(request, FONTS).catch(() => fetch(request))); return; }
  if (url.hostname === 'fonts.gstatic.com') { event.respondWith(cacheFirst(request, FONTS).catch(() => fetch(request))); }
});
